In [2]:
import cv2 as cv

In [3]:
import numpy as np

# LAPLACIAN FLITER

In [25]:
a=cv.imread("C:\\Users\SYS76\\Desktop\\maxresdefault.jpg",0)

In [26]:
cv.imshow("image",a)
cv.waitKey(0)
cv.destroyAllWindows()

In [38]:
lap=cv.Laplacian(a,cv.CV_64F,ksize=1)
lap


array([[ 344., -226.,   -7., ...,   -8., -109.,  178.],
       [ 319., -153.,   22., ...,   -6.,  -86.,  192.],
       [ 328., -183.,  -24., ...,    3.,  -89.,  149.],
       ...,
       [ 255., -120.,   15., ...,   -6., -125.,  246.],
       [ 260., -125.,   11., ...,   -3., -134.,  227.],
       [ 254., -152.,  -20., ...,   40.,  -98.,  236.]])

In [39]:
lap=np.uint8(np.absolute(lap))
cv.imshow("LAP",lap)
cv.imshow("image",a)
cv.waitKey(0)
cv.destroyAllWindows()

# SOBAL FILTER


In [54]:
a=cv.imread("C:\\Users\SYS76\\Desktop\\maxresdefault.jpg",0)


In [74]:
sobelx=cv.Sobel(a,cv.CV_64F,1,0,ksize=5)
print(sobelx)
sobelx=np.uint8(np.absolute(sobelx))
cv.imshow("image",a)
cv.imshow("soblex",sobelx)
cv.waitKey(0)
cv.destroyAllWindows()

[[    0.  4276.  1246. ...  -906. -2514.     0.]
 [    0.  4353.  1377. ...  -907. -2497.     0.]
 [    0.  4444.  1641. ...  -881. -2497.     0.]
 ...
 [    0.  4010.  2086. ... -1827. -3833.     0.]
 [    0.  3995.  2044. ... -1605. -3529.     0.]
 [    0.  4010.  2016. ... -1488. -3380.     0.]]


In [72]:
sobely=cv.Sobel(a,cv.CV_64F,0,1,ksize=5)
print(sobely)
cv.imshow("image",a)
sobely=np.uint8(np.absolute(sobely))
cv.imshow("sobley",sobely)
cv.waitKey(0)
cv.destroyAllWindows()

[[   0.    0.    0. ...    0.    0.    0.]
 [-158.  -81.  127. ...  -11.    5.   22.]
 [-270. -256. -109. ...   17.   27.   10.]
 ...
 [ -42.  -72. -116. ... -675. -415. -260.]
 [ 278.  293.  280. ... -771. -505. -356.]
 [   0.    0.    0. ...    0.    0.    0.]]
