In [1]:
import cv2 
import numpy as np


In [2]:
img=cv2.imread("C:\\Users\\SYS76\\Downloads\\download.jfif")

In [3]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [4]:
vec = imgrgb.reshape((-1,3))
vec

array([[164, 101,  48],
       [164, 101,  48],
       [167, 102,  48],
       ...,
       [106,  97,  88],
       [ 99,  86,  77],
       [105,  93,  81]], dtype=uint8)

In [5]:
vec=np.float32(vec)
vec

array([[164., 101.,  48.],
       [164., 101.,  48.],
       [167., 102.,  48.],
       ...,
       [106.,  97.,  88.],
       [ 99.,  86.,  77.],
       [105.,  93.,  81.]], dtype=float32)

In [6]:
criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

In [7]:
k=3
attempts=100

In [8]:
compactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [9]:
center = np.uint8(center)
center

array([[206, 140,  74],
       [ 70,  61,  56],
       [213, 202, 190]], dtype=uint8)

In [10]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[206, 140,  74],
        [206, 140,  74],
        [206, 140,  74],
        ...,
        [206, 140,  74],
        [206, 140,  74],
        [206, 140,  74]],

       [[206, 140,  74],
        [206, 140,  74],
        [206, 140,  74],
        ...,
        [206, 140,  74],
        [206, 140,  74],
        [206, 140,  74]],

       [[206, 140,  74],
        [206, 140,  74],
        [206, 140,  74],
        ...,
        [206, 140,  74],
        [206, 140,  74],
        [206, 140,  74]],

       ...,

       [[ 70,  61,  56],
        [ 70,  61,  56],
        [ 70,  61,  56],
        ...,
        [ 70,  61,  56],
        [ 70,  61,  56],
        [ 70,  61,  56]],

       [[ 70,  61,  56],
        [ 70,  61,  56],
        [ 70,  61,  56],
        ...,
        [ 70,  61,  56],
        [206, 140,  74],
        [ 70,  61,  56]],

       [[ 70,  61,  56],
        [ 70,  61,  56],
        [ 70,  61,  56],
        ...,
        [ 70,  61,  56],
        [ 70,  61,  56],
        [ 70,  61,  56]]

In [11]:
cv2.imshow("Orginal",img)
cv2.imshow("Segmented",res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# pyrmean



In [12]:
import cv2
import numpy as np

In [13]:
image=cv2.imread("C:\\Users\\SYS76\\Downloads\\download.jfif")

In [18]:
segmented_img=cv2.pyrMeanShiftFiltering(image,40,50)

In [ ]:
cv2.imshow("Orginal_Image",img)
cv2.imshow("Segmented_Image",segmented_img)
cv2.waitKey(0)
cv2.destroyAllWindows()