  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/3e/77/dab54fe647a08ee4253963bcd8f9cf17509c8ca64d6335141422fe2e2114/scipy-1.13.1-cp39-cp39-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.6 kB 330.3 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/60.6 kB 650.2 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 457.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/46.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/46.2 MB 7.7 MB/s eta 0:00:07
   ---------------------------------------- 0.4/46.2 MB 6.3 MB/s eta 0:00:08
    --------------------------------------- 0.7/46.2 MB 6.7 MB/s eta 0:00:07
    --------------------------------------- 1.1/46.2 MB 6.8 MB/s eta 0:00:07
   - -------------------------------------- 1.5/46.2 MB 7.3 MB/s eta 0:00:07
   - -------------------------

In [2]:
import numpy as np

In [3]:
ar1=np.array(6)
ar1

array(6)

In [4]:
ar2=np.array([[2,3,4,5,6],[1,2,3,4,5]])



In [5]:
ar2

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [7]:

ar3=np.array([[1,2,3,4],[2,3,4,5]])
ar3

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [8]:

zero_array=np.zeros((2,2))
zero_array

array([[0., 0.],
       [0., 0.]])

In [9]:
one_array=np.ones((2,2))
one_array

array([[1., 1.],
       [1., 1.]])

In [10]:

ar4=np.arange(2,15,3)
ar4

array([ 2,  5,  8, 11, 14])

In [11]:

ar5=np.transpose(ar3)
ar5

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [13]:
ar6=np.ravel(ar5)
ar6

array([1, 2, 2, 3, 3, 4, 4, 5])

In [14]:
a1=np.array([2,2])
a2=np.array([4,2])
a1

array([2, 2])

In [15]:
concat=np.concatenate((a1,a2))
concat

array([2, 2, 4, 2])

In [16]:

hori=np.hstack((a1,a2))
hori

array([2, 2, 4, 2])

In [17]:
vert=np.vstack((a1,a2))

In [19]:
vert

array([[2, 2],
       [4, 2]])

In [37]:
mat1=np.array([[1,2,3],[4,7,6],[5,8,9]])

In [38]:
mat1

array([[1, 2, 3],
       [4, 7, 6],
       [5, 8, 9]])

In [39]:
det_of_mat1=np.linalg.det(mat1)


In [40]:
det_of_mat1

-5.999999999999997

In [45]:
inverse=np.linalg.inv(mat1)

In [46]:
inverse

array([[-2.5       , -1.        ,  1.5       ],
       [ 1.        ,  1.        , -1.        ],
       [ 0.5       , -0.33333333,  0.16666667]])

In [47]:
Dense=np.array([[1,0,3,0],[4,0,7,0],[5,0,8,0],[0,6,0,9]])

In [49]:
Dense

array([[1, 0, 3, 0],
       [4, 0, 7, 0],
       [5, 0, 8, 0],
       [0, 6, 0, 9]])

In [56]:
from scipy.sparse import csr_matrix

In [61]:
sparse=csr_matrix(Dense)

In [62]:
sparse

<4x4 sparse matrix of type '<class 'numpy.int32'>'
	with 8 stored elements in Compressed Sparse Row format>

In [63]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 0)	4
  (1, 2)	7
  (2, 0)	5
  (2, 2)	8
  (3, 1)	6
  (3, 3)	9
